#!/bin/bash

# LBLUE is used for title text
# GREEN is used for prompts
# DARKGREY is used to show any commands run
export LBLUE='\033[1;34m'
export GREEN='\033[0;32m'
export RED='\033[0;31m'
export DARKGREY='\033[1;30m'
export NC='\033[0m'

envfn=get_info.env.sh

# the script is best used via source
[[ "${BASH_SOURCE[0]}" != "${0}" ]] || echo -e "\n${RED}I recommend running this script via source$NC\n\nUse ..\n    . get_info.sh\n.. to allow the script to set environment variables so you don't have to reenter values on the next run\n"

### Utilities

# url encode (requires python3)
function urlencode {
  python3 -c "import urllib.parse; print(urllib.parse.quote(input()))" <<< "$1"
}

# Run a simple command with a dark grey echo
function gocmd {
  cmd="$@"
  echo -e "$DARKGREY$cmd$NC"
  eval "$cmd"
}

# Start off the output env file
echo -e "#!/bin/bash\n#\n# basecamp3dumper env variables (generated by obtainAccessToken.sh)\n#\n" > $envfn




### PART 1: Obtain the details for the basecamp integration so we can get a code
echo -e "\n${LBLUE}Details for the basecamp integration$NC"

echo -e -n "${GREEN}Do you have the details of an existing basecamp integration? [no]: $NC"; read v
if [[ "$v" == "no" || "$v" == "" ]]; then
  echo -e "Ok. I'm about to open a browser tab that will show your basecamp integrations.\n  Please create a new integration on this page then come back here to enter the provided details.\n  ${LBLUE}Redirect URL:${NC} The redirect can be any url with a hostname you trust, with any path you see fit (whether it exists or not)\n"

  echo -e -n "${GREEN}Press enter to continue...$NC"; read v

  gocmd open https://launchpad.37signals.com/integrations
fi

echo -e -n "${GREEN}Client id [$BC3_CLIENT_ID]: $NC"; read v
if [[ "$v" == "" ]]; then v="$BC3_CLIENT_ID"; fi
export BC3_CLIENT_ID="$v"
echo "export BC3_CLIENT_ID='$v'" >> "$envfn"

echo -e -n "${GREEN}Client secret [$BC3_CLIENT_SECRET]: $NC"; read v
if [[ "$v" == "" ]]; then v="$BC3_CLIENT_SECRET"; fi
export BC3_CLIENT_SECRET="$v"
echo "export BC3_CLIENT_SECRET='$v'" >> "$envfn"

echo -e -n "${GREEN}Client redirect [$BC3_CLIENT_REDIRECT]: $NC"; read v
if [[ "$v" == "" ]]; then v="$BC3_CLIENT_REDIRECT"; fi
export BC3_CLIENT_REDIRECT="$v"
echo "export BC3_CLIENT_REDIRECT='$v'" >> "$envfn"
redirect_url=`urlencode "$BC3_CLIENT_REDIRECT"`




### PART 2: Get a code from basecamp which will be used to obtain a token
echo -e "\n${LBLUE}Obtain an oauth code$NC"

gocmd "open 'https://launchpad.37signals.com/authorization/new?type=web_server&response_type=code&redirect_uri=$redirect_url&client_id=$BC3_CLIENT_ID'"

echo -e -n "${GREEN}Type the code shown in the URL on the redirect page: $NC"; read v
export BC3_CODE="$v"
echo "export BC3_CODE='$v'" >> "$envfn"




### PART 3: Get a token from basecamp
echo -e "\n${LBLUE}Obtain a token$NC"

cmd="curl -X POST 'https://launchpad.37signals.com/authorization/token?type=web_server&client_id=$BC3_CLIENT_ID&redirect_uri=$redirect_url&client_secret=$BC3_CLIENT_SECRET&code=$BC3_CODE' | jq -r '.access_token'"
echo -e "$DARKGREY$cmd$NC"
export BC3_TOKEN=`eval "$cmd"`
echo "export BC3_TOKEN='$BC3_TOKEN'" >> "$envfn"




### PART 4: Additional info for running the node app
echo -e "\n${LBLUE}Get additional info$NC"

echo -e -n "${GREEN}Enter your email address for the script to use [$BC3_EMAIL]: $NC"; read v
if [[ "$v" == "" ]]; then v="$BC3_EMAIL"; fi
export BC3_EMAIL="$v"
echo "export BC3_EMAIL='$v'" >> "$envfn"

echo -e -n "${GREEN}Enter the account number to download resources from (it it the first number on the url of your page on basecamp) [$BC3_ACCOUNT]: $NC"; read v
if [[ "$v" == "" ]]; then v="$BC3_ACCOUNT"; fi
export BC3_ACCOUNT="$v"
echo "export BC3_ACCOUNT='$v'" >> "$envfn"

echo

gocmd cat "$envfn"

echo

gocmd node index.js --help

echo -e "\nRun the resource downloading node app using ..\n    npm install\n    node index.js\n"
echo -e "\n${LBLUE}All done$NC"
